Sloeber/arduino-eclipse-plugin

Eclipse update site/WebContent/faq.shtml, Eclipse update site/WebContent/how_to.shtml, Eclipse update site/WebContent/js/app.js
Small changes to test web server configuration and deep linking solution viability
=> Website fixes

.gitignore, it.baeyens.cdt.refactor/.gitignore
Just added two folders in the `.gitignore` files: I believe they just slept out.
=> Little cleanup

it.baeyens.arduino.core/src/it/baeyens/arduino/actions/BuildHandler.java, it.baeyens.arduino.core/src/it/baeyens/arduino/listeners/ConfigurationChangeListener.java, it.baeyens.arduino.core/src/it/baeyens/arduino/toolchain/ArduinoLanguageProvider.java, it.baeyens.arduino.core/src/it/baeyens/arduino/tools/ArduinoBoards.java, it.baeyens.arduino.core/src/it/baeyens/arduino/tools/ArduinoHelpers.java, it.baeyens.arduino.core/src/it/baeyens/arduino/tools/ArduinoLibraries.java, it.baeyens.arduino.core/src/it/baeyens/arduino/ui/ArduinoCompileProperties.java, it.baeyens.arduino.core/src/it/baeyens/arduino/ui/ArduinoPropertyPage.java, it.baeyens.arduino.core/src/it/baeyens/arduino/ui/ArduinoSampleSelector.java, it.baeyens.arduino.core/src/it/baeyens/arduino/ui/ArduinoSelectionPage.java, it.baeyens.arduino.core/src/it/baeyens/arduino/ui/LabelCombo.java, it.baeyens.arduino.core/src/it/baeyens/arduino/ui/NewArduinoSketchWizardBoardPage.java, it.baeyens.arduino.core/src/it/baeyens/arduino/ui/NewArduinoSketchWizardCodeSelectionPage.java, it.baeyens.arduino.core/src/it/baeyens/arduino/ui/activator.java, it.baeyens.arduino.product/arduino.product
Quite a few changes to have better support for multiconfiguration.
Basically these changes allow to have multiple configurations with different boards.
This is the starting point to allow for local debugging and unit testing each with their own config.
IMHO the change is 100% downwards compatible.
=> Multi configuration improvements

it.baeyens.arduino.core/src/it/baeyens/arduino/ui/ArduinoSampleSelector.java
tested on osx, unfortunately not on windows or linux
please have a look and comment
=> fix for #248

it.baeyens.arduino.core/src/it/baeyens/arduino/ui/Import_Arduino_Libraries_Page.java
This provides the first half of issue #247. Next will be to remove libraries if they are deselected.
=> Checks tickboxes of already added libraries in dialog to add libraries.

it.baeyens.arduino.core/src/it/baeyens/arduino/tools/ArduinoLibraries.java, it.baeyens.arduino.core/src/it/baeyens/arduino/ui/Import_Arduino_Libraries_Page.java
This completes the fix for issue #247. Libraries are now added or removed based on the selection of checked tickboxes..
=> Removes libraries that are not selected in Import_Arduino_Libraries_Page

it.baeyens.arduino.core/src/it/baeyens/arduino/ui/ArduinoSelectionPage.java
=> Removes com port validation during sketch creation.

win32x32.cmd, win32x64.cmd
Update launchers to point to new executable name
=> #291 windows starters no longer work

it.baeyens.arduino.core/src/it/baeyens/arduino/managers/ArduinoManager.java, it.baeyens.arduino.core/src/it/baeyens/arduino/ui/Activator.java
* Added UI to IDE Installer Job
* Refactored some complexity
* Code formatting
=> #306 Remove the ArduinoIDE dependency

it.baeyens.arduino.product/arduino.product
Removed org.eclipse.epp.package.common.feature
=> #371 remove oomph from product

it.baeyens.arduino.product/arduino.product
* Added recommended start levels to product file
* new pr to retrigger the build
=> #321 - Frameworkerrors during startup

it.baeyens.arduino.updatesite/pom.xml
* Removed includeAllDependencies
=> 389: Add category to update site

it.baeyens.arduino.feature/build.properties, it.baeyens.arduino.feature/epl-v10.html, it.baeyens.arduino.feature/feature.properties, it.baeyens.arduino.feature/feature.xml, it.baeyens.arduino.feature/license-AVR.html, it.baeyens.arduino.feature/license-Eclipse.html, it.baeyens.arduino.feature/license.html
* Added EPL license
* Added License for AVR
* Added License for Eclipse
* Renamed licence.html to license.html
* Included license files in build properties
* Added epl-v10.html
Tested the license and the feature descriptions during installation: All good.
=> #390: Fix the license

it.baeyens.arduino.common/src/it/baeyens/arduino/arduino/Serial.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S00117 Local variable and method parameter names should comply with a naming convention.
squid:S1181 Throwable and Error should not be caught.
squid:S1213 The members of an interface declaration or class should appear in a pre-defined order.
squid:S00116 Field names should comply with a naming convention.
squid:UselessParenthesesCheck Useless parentheses around expressions should be removed to prevent any misunderstanding.
squid:S1197 Array designators "[]" should be on the type, not the variable.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS00117
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1181 …
=> multiple code improvements: squid:S00117, squid:S1181, squid:S1213, squid:S00116, squid:UselessParenthesesCheck, squid:S1197

it.baeyens.arduino.common/src/it/baeyens/arduino/common/Activator.java, it.baeyens.arduino.common/src/it/baeyens/arduino/common/Common.java, it.baeyens.arduino.common/src/it/baeyens/arduino/common/Const.java, it.baeyens.arduino.core/src/it/baeyens/arduino/communication/ArduinoSerial.java, it.baeyens.arduino.core/src/it/baeyens/arduino/listeners/ConfigurationChangeListener.java, it.baeyens.arduino.core/src/it/baeyens/arduino/listeners/IndexerListener.java, it.baeyens.arduino.core/src/it/baeyens/arduino/natures/ArduinoNature.java, it.baeyens.arduino.core/src/it/baeyens/arduino/toolchain/ArchiveNameProvider.java, it.baeyens.arduino.core/src/it/baeyens/arduino/toolchain/ArduinoLanguageProvider.java, it.baeyens.arduino.core/src/it/baeyens/arduino/toolchain/LinkNameProvider.java, it.baeyens.arduino.core/src/it/baeyens/arduino/toolchain/hexNameProvider.java, it.baeyens.arduino.core/src/it/baeyens/arduino/tools/Boards.java, it.baeyens.arduino.core/src/it/baeyens/arduino/tools/Helpers.java, it.baeyens.arduino.core/src/it/baeyens/arduino/tools/uploaders/UploadSketchWrapper.java, it.baeyens.arduino.core/src/it/baeyens/arduino/ui/CompileProperties.java, it.baeyens.arduino.core/src/it/baeyens/arduino/ui/ExplorerLabelDecorator.java, it.baeyens.arduino.monitor/src/it/baeyens/arduino/monitor/views/OpenSerialDialogBox.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S00115 Constant names should comply with a naming convention.
squid:S1213 The members of an interface declaration or class should appear in a pre-defined order.
squid:S1066 Collapsible "if" statements should be merged.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS00115
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1213
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1066
Please let me know if you have any questions.
George Kankava
=> multiple code improvements: squid:S00115, squid:S1213, squid:S1118, squid:S1066

it.baeyens.arduino.core/src/it/baeyens/arduino/communication/ArduinoSerial.java
This pull request is focused on resolving occurrences of Sonar rules
squid:CommentedOutCodeLine - Sections of code should not be "commented out".
squid:S1118 - Utility classes should not have public constructors.
squid:S00117 - Local variable and method parameter names should comply with a naming convention.
squid:S1155 - Collection.isEmpty() should be used to test for emptiness.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:CommentedOutCodeLine
https://dev.eclipse.org/sonar/rules/show/squid:S1118
https://dev.eclipse.org/sonar/rules/show/squid:S00117
https://dev.eclipse.org/sonar/rules/show/squid:S1155
Please let me know if you have any questions.
George Kankava
=> multiple code improvements: squid:CommentedOutCodeLine, squid:S1118, squid:S00117, squid:S1155

it.baeyens.arduino.core/config/pre_processing_platform_default.txt, it.baeyens.arduino.core/src/it/baeyens/arduino/tools/PasswordManager.java, it.baeyens.arduino.core/src/it/baeyens/arduino/tools/uploaders/SSHUpload.java, it.baeyens.arduino.core/src/it/baeyens/arduino/tools/uploaders/UploadSketchWrapper.java
It seemed the passworddialog was no longer on a UI thread making it fail
with a null pointer.
For the yun shield there is a tools.[tool]_network.upload.pattern
command for the upload
For the yun shield the -v is not optional
=> Make yunshield work

it.baeyens.arduino.parent/pom.xml
Added neon support and made it the default build target.
=> Neon Support #484

io.sloeber.updatesite/category.xml
* Added Nebula to the list of searchable repos
=> Use the nebula package code directly instead of the copy. #565

io.sloeber.parent/pom.xml
=> Add support for Oxygen #574

io.sloeber.updatesite/category.xml
* Added nebula feature to update site as dependency
=> #565 Use the nebula package code directly instead of the copy.

io.sloeber.updatesite/category.xml
* Added nested category for update site
=> #603 add gnu ARM open ocd debug launch

io.sloeber.feature/feature.xml, io.sloeber.parent/pom.xml, io.sloeber.updatesite/category.xml, readme.md
also forced inclusion of the launch configurations.
As there was no code dependency but this should be installed I added a dependency
=> #603 moved to io.sloeber update site

io.sloeber.ui/src/io/sloeber/ui/project/properties/BoardSelectionPage.java
Task-Url:
https://github.com/jantje/arduino-eclipse-plugin/issues/issues/615
- Combo is properly initialized with selection
- Combo is no longer hidden
- long pathnames are shortened for display
=> 615: New Sketch wizard does not work on Mac

io.sloeber.core/config/pre_processing_platform_default.txt, io.sloeber.core/src/io/sloeber/core/common/IndexHelper.java, io.sloeber.core/src/io/sloeber/core/tools/uploaders/arduinoUploader.java, io.sloeber.ui/src/io/sloeber/ui/PasswordDialog.java
This is part one as I also need to look at ssh yun
But as these are functionally not related I want to push this part already.
=> Fix upload problems for AUTH OAT

io.sloeber.core/src/io/sloeber/core/toolchain/ArduinoGnuMakefileGenerator.java, io.sloeber.core/src/io/sloeber/core/toolchain/ArduinoManagedBuildGnuToolInfo.java
=> #639 making all files os dependent

io.sloeber.ui/src/io/sloeber/ui/project/properties/BoardSelectionPage.java
=> #645 make dialog box pop up when com port is selected and password

io.sloeber.core/src/io/sloeber/core/tools/Helpers.java
=> - fix for issue #683

io.sloeber.core/src/io/sloeber/core/api/LibraryManager.java, io.sloeber.ui/src/io/sloeber/ui/preferences/LibrarySelectionPage.java
- some formatting
- library selection: added ability to cancel library update job (libraries download & install)
- library selection: update job can be started only once at a time
=> LibraryManager - minor changes & fixes

io.sloeber.core/src/io/sloeber/core/common/ConfigurationPreferences.java, io.sloeber.core/src/io/sloeber/core/tools/uploaders/arduinoUploader.java
Minor changes and improve user experiance when upgrading
=> Release 4.1

io.sloeber.core/src/io/sloeber/core/tools/Libraries.java
I had the same issue, this fix should solve this problem.
=> can no longer add a library to the project !! #755

io.sloeber.ui/plugin.xml
=> Fix the colors of the plotter #876

io.sloeber.ui/src/io/sloeber/ui/actions/UploadProjectHandler.java
=> On fast machines when the build fails the upload is still executed #878

io.sloeber.parent/pom.xml
forgot to push my last commit..
This one makes the -Poxygen obsolete.
=> Cannot IDE/plugin build on Mac OS X #898

io.sloeber.core/src/io/sloeber/core/api/BoardDescriptor.java, io.sloeber.core/src/io/sloeber/core/api/CompileOptions.java, io.sloeber.core/src/io/sloeber/core/tools/ShouldHaveBeenInCDT.java, io.sloeber.ui/src/io/sloeber/ui/Messages.java, io.sloeber.ui/src/io/sloeber/ui/helpers/MyPreferences.java, io.sloeber.ui/src/io/sloeber/ui/messages.properties, io.sloeber.ui/src/io/sloeber/ui/preferences/PreferencePage.java, io.sloeber.ui/src/io/sloeber/ui/wizard/newsketch/NewSketchWizard.java
Enable parallel build by default in new projects, that should make builds quite a bit faster.
=> parallel build by default in new project

io.sloeber.core/src/io/sloeber/core/api/PackageManager.java
A proposed basic fox for #1114.
=> Fix for #1114: a basic support for multi-redirections.

io.sloeber.core/src/io/sloeber/core/api/PackageManager.java
A small improvement to the #1114 fix. It introduces a max http redirection counter to prevent unwanted redirection loop.
=> Fix/improvement for #1114: proposed solution for redirection counter.

io.sloeber.core/src/io/sloeber/core/api/PackageManager.java
resolves #1157
@jantje what do you think about it?
=> accept empty lines in json list

io.sloeber.core/src/io/sloeber/core/api/BoardDescriptor.java, io.sloeber.core/src/io/sloeber/core/api/PackageManager.java, io.sloeber.core/src/io/sloeber/core/common/ConfigurationPreferences.java, io.sloeber.core/src/io/sloeber/core/common/Const.java, io.sloeber.core/src/io/sloeber/core/managers/ArduinoPlatform.java, io.sloeber.core/src/io/sloeber/core/managers/Board.java, io.sloeber.core/src/io/sloeber/core/managers/InternalPackageManager.java, io.sloeber.core/src/io/sloeber/core/managers/Package.java, io.sloeber.core/src/io/sloeber/core/managers/PackageIndex.java, io.sloeber.core/src/io/sloeber/core/managers/Tool.java, io.sloeber.core/src/io/sloeber/core/managers/ToolDependency.java, io.sloeber.core/src/io/sloeber/core/managers/ToolSystem.java, io.sloeber.core/src/io/sloeber/core/managers/WorkAround.java, io.sloeber.core/src/io/sloeber/core/tools/Helpers.java, io.sloeber.core/src/io/sloeber/core/tools/Programmers.java, io.sloeber.core/src/io/sloeber/core/tools/TxtFile.java, io.sloeber.core/src/io/sloeber/core/tools/Version.java, io.sloeber.product/META-INF/MANIFEST.MF, io.sloeber.tests/src/io/sloeber/core/CompileAndUpload.java, io.sloeber.tests/src/io/sloeber/core/CreateAndCompileDefaultInoOnAllBoardsTest.java, io.sloeber.tests/src/io/sloeber/core/MySystem.java, io.sloeber.ui/src/io/sloeber/ui/monitor/internal/SerialListener.java, io.sloeber.ui/src/io/sloeber/ui/project/properties/BoardSelectionPage.java
Test are fine now on linux and windows
=> Centralize workarounds

io.sloeber.core/src/io/sloeber/core/api/Sketch.java, io.sloeber.ui/src/io/sloeber/ui/Messages.java, io.sloeber.ui/src/io/sloeber/ui/actions/UploadProjectHandler.java, io.sloeber.ui/src/io/sloeber/ui/helpers/MyPreferences.java, io.sloeber.ui/src/io/sloeber/ui/messages.properties, io.sloeber.ui/src/io/sloeber/ui/messages_it.properties, io.sloeber.ui/src/io/sloeber/ui/messages_nl.properties, io.sloeber.ui/src/io/sloeber/ui/monitor/internal/SerialListener.java, io.sloeber.ui/src/io/sloeber/ui/preferences/PreferencePage.java
Hi Jan,
Are you interested in this change? I find it convenient.
I tried to squash the commits, but I don't think it worked.
Does github have a way to do it on the website? I can't see how to do it in a pull request, when looking at the branch, or in the desktop app.
=> Automatically switch to serial monitor after successful upload

io.sloeber.parent/pom.xml, io.sloeber.product.sdk/arduino.product, io.sloeber.product/arduino.product, io.sloeber.updatesite/category.xml
=> Product maintenance #1252

io.sloeber.core/src/io/sloeber/core/tools/ExternalCommandLauncher.java
=> fix for unix systems

.github/workflows/maven.yml, io.sloeber.parent/pom.xml
=> Create build action #1356

io.sloeber.product/sloeber.target
=> sloeber.target is out of sync #1428

io.sloeber.core/src/io/sloeber/core/api/BoardDescription.java
Tested this with the test scripts on linux and windows
Seems safe
=> #1410 uploads seem to work except for #1437

io.sloeber.product.sdk/arduino.product, io.sloeber.product/arduino.product
Replace httpclient45 with httpclient5
=> Replace httpclient45 with httpclient5 #145

io.sloeber.core/src/io/sloeber/core/api/Serial.java, io.sloeber.core/src/io/sloeber/core/common/Const.java, io.sloeber.core/src/io/sloeber/core/communication/ArduinoSerial.java, io.sloeber.tests/src/io/sloeber/core/MySystem.java
Hope this triggers the actions build
=> #1444 allow for custom pattern matching

.github/workflows/maven.yml, io.sloeber.parent/pom.xml
Apple has moved to ARM architecture.
=> Build for ARM

io.sloeber.core/src/io/sloeber/core/api/ConfigurationDescriptor.java, io.sloeber.core/src/io/sloeber/core/api/Sketch.java, io.sloeber.core/src/io/sloeber/core/api/SloeberProject.java, io.sloeber.core/src/io/sloeber/core/common/Const.java, io.sloeber.core/src/io/sloeber/core/listeners/IndexerController.java, io.sloeber.core/src/io/sloeber/core/listeners/IndexerListener.java, io.sloeber.core/src/io/sloeber/core/listeners/resourceChangeListener.java
Creating pull request so it can be tested
=> Completely redesigned the indexcontroller #1491
