Sloeber/arduino-eclipse-plugin

it.baeyens.arduino.core/src/it/baeyens/arduino/communication/ArduinoSerial.java

Mimicking the equivalent code on Arduino IDE I changed the delay between each retry to 250ms and prolonged the delay after the reset request to 300ms.
I've added a debug statement which reported it requires 3 secs for my original Arduino Micro to reconnect on the programming COM port.
I've updated the comment and added a FIXME comment regarding the reccommended MacOS platform check.

Fix for issue #209

---

it.baeyens.arduino.common/src/it/baeyens/arduino/arduino/Serial.java

Optimized regexp to filter only serial and usbserial ports, excluding bluetooth ports that could slow down the detection process.

Speed up serial port detection in OSX, excluding bluetooth ports

---

.travis.yml
it.baeyens.arduino.parent/pom.xml

* Upgraded Tycho to 0.24
* Instructed Tycho to use java 8 instead of 7

#334 upgrade to java 8

---

it.baeyens.arduino.common/src/it/baeyens/arduino/arduino/Serial.java
it.baeyens.arduino.monitor/src/it/baeyens/arduino/monitor/views/Messages.java
it.baeyens.arduino.monitor/src/it/baeyens/arduino/monitor/views/OpenSerialDialogBox.java
it.baeyens.arduino.monitor/src/it/baeyens/arduino/monitor/views/SerialMonitor.java
it.baeyens.arduino.monitor/src/it/baeyens/arduino/monitor/views/messages.properties

Added a boolean flag for a serial connection (COM Port) to configure the RST/DTR flags of the serial connection.
I testet it and can confirm it fixes #394 for me.

Fix for #394, adding config parameter for RST/DTR flags in serial connection

---

it.baeyens.arduino.common/src/it/baeyens/arduino/common/InstancePreferences.java

setPrivateLibraryPaths method used "\n" for joining folder names, while
the getter uses File.pathSeparator for splitting. I harmonised to the latter.
Multi private library functionality is working now on (my) Mac too.

#409: Fixed inconsistent path separator in get/setPrivateLibraryPaths.

---

it.baeyens.arduino.core/src/it/baeyens/arduino/managers/ArduinoPlatform.java
it.baeyens.arduino.core/src/it/baeyens/arduino/managers/Manager.java

This pull request is focused on resolving occurrences of Sonar rules
squid:S1118 - Utility classes should not have public constructors
squid:S1197 - Array designators "[]" should be on the type, not the variable.
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
squid:CommentedOutCodeLine - Sections of code should not be "commented out".
squid:S2864 - "entrySet()" should be iterated when both the key and value are needed.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1118
https://dev.eclipse.org/sonar/rules/show/squid:S1197
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
https://dev.eclipse.org/sonar/rules/show/squid:CommentedOutCodeLine …

multiple code improvements: squid:S1118, squid:S1197, squid:UselessParenthesesCheck, squid:CommentedOutCodeLine, squid:S2864

---

it.baeyens.arduino.core/src/it/baeyens/arduino/actions/UploadProjectHandler.java

There is no standard way to check if CDT build succeeded or not.
However, when I faced a similar problem 5 years ago or so, someone gave me an advice to check if the project has  any CDT error markers. Usually if there are error markers after build then they were generated on this last build and thus this build was not successful.
I'm not sure if this logic will never fire false-positives (e.g. the project has CDT error markers, but still builds successfully), but I've never faced such behavior.
This commit implements the described build error detector during the "build before upload" phase.

Issue #284: Upload occurs even if build fails.

---

it.baeyens.arduino.common/src/it/baeyens/arduino/common/Defaults.java
it.baeyens.arduino.common/src/it/baeyens/arduino/common/InstancePreferences.java
it.baeyens.arduino.core/src/it/baeyens/arduino/ui/PreferencePage.java

see https://github.com/jantje/arduino-eclipse-plugin/issues/408
Eclipse checked boolean preference value against 'default' value and just removed the preference from store if new value was equal to default value (false for boolean values by default).
This commit overrides default values for boolean preferences, making them the same in default preference initializer and in preference page editor.

Fix for preference page not saving some preferences

---

io.sloeber.product/arduino.product
io.sloeber.product/config/mac/config.ini
io.sloeber.product/neon-cdt-nebula.target

Also remove PDE and JDT dependency, create a target file and change config.ini to put the default workspace in path ~/Documents/sloeber-worksapce as default instead of the invisible and non-selectable application root folder. This must also be best practice on Linux and Windows with multiple users: each user gets his own workspace.

606: Remove dependency on org.eclipse.wb.core.lib

---

website/WebContent/fragments/files.php

Due to the baeyens.it to sloeber.io and the clean that didn't work I think 3.1 was in the 4.0 files.
I reuploaded the files so now the listing needs to be updated on the web site.
I did so directly on the server but this is a coipy so when the github content is pushed the links still work.

Link to new files

---

io.sloeber.core/src/io/sloeber/core/api/Defaults.java
io.sloeber.core/src/io/sloeber/core/api/LibraryManager.java
io.sloeber.core/src/io/sloeber/core/managers/LibraryIndex.java
io.sloeber.core/src/io/sloeber/core/managers/Manager.java

I broke installation of default libraries with my prevoius commits... Now it's fixed.
BTW:
"Errors/Warnings" setting screenshots (in source code: images_plugin_dev_setup) are probably outdated checks for NLS strings are ignored (Screenshot-Preferences 1.png)
It is better to create small poll requests rather than the big one as the first was?

Fixed installation of defaults libraries after first run

---

io.sloeber.core/src/io/sloeber/core/api/Defaults.java

On windows the default is for Arduino to put the sketchbook folder in the users Documents folder. 
this is to resolve #1098

Adding the Documents folder to the default path for Sloeber on Windows

---

.travis.yml
io.sloeber.core/src/io/sloeber/core/common/Common.java
io.sloeber.core/src/io/sloeber/core/managers/WorkAround.java
io.sloeber.core/src/io/sloeber/core/tools/TxtFile.java
io.sloeber.tests/src/io/sloeber/core/RegressionTest.java

Seems the workaround solution will only work on windows.
Why did my tests succeed?

Issue #1175

---

io.sloeber.ui/src/io/sloeber/ui/monitor/internal/SerialListener.java
io.sloeber.ui/src/io/sloeber/ui/monitor/views/SerialMonitor.java

This needs to be fixed before I can redo the timestamp code in SerialMonitor.

Fix for #1190 Serial monitor colours not right

---

io.sloeber.core/src/io/sloeber/core/api/CodeDescriptor.java
io.sloeber.ui/src/io/sloeber/ui/Messages.java
io.sloeber.ui/src/io/sloeber/ui/messages.properties
io.sloeber.ui/src/io/sloeber/ui/wizard/newsketch/NewSketchWizardCodeSelectionPage.java

I still need to test this, I have problems building the SDK on Windows 10.
fixes #1228

explicit no file option for new sketch

---

io.sloeber.ui/src/io/sloeber/ui/preferences/LibrarySelectionPage.java

This fix allows to modify libraries many times
without need to restarting Preferences dialog.

Library Preferences page was improved.

---

.gitignore

the `.project` files and the `.settings` folders should never get into the repository as they contain values specific to the local dev environment (sometimes also things you want to keep secret). Also, those files should be rebuilt by Eclipse upon importing the maven modules, so they can be considered _generated_ files.

adds eclipse settings to ignores

---

io.sloeber.core.nl1/META-INF/MANIFEST.MF
io.sloeber.core/META-INF/MANIFEST.MF
io.sloeber.product.sdk/META-INF/MANIFEST.MF
io.sloeber.product/META-INF/MANIFEST.MF
io.sloeber.tests/META-INF/MANIFEST.MF
io.sloeber.ui/META-INF/MANIFEST.MF

Java11 compatible

---

.github/workflows/maven.yml

The nls1 requires java 17 but the compile uses Java 11. This updates the compile to Java 17. Alternatively, the nls bundle may be downgraded to Java 11

Build with Java 17

---

io.sloeber.parent/pom.xml
io.sloeber.product.sdk/arduino.product
io.sloeber.product/arduino.product
io.sloeber.product/sloeber.target
io.sloeber.updatesite/category.xml

The repositories sometimes refer to snapshots and sometimes to the latest. To avoid nebula problems as we saw, I propose moving to a fixed nebula repository release 2.7.2.
I also resolved other potential problems in this area.

Move to fixed nebula

---

build_then_launch.sh
io.sloeber.product/pom.xml
readme.md

* Changed Linux package format to `tar.gz`
Fixes [issue 1577](https://github.com/Sloeber/arduino-eclipse-plugin/issues/1577)
Fixes [issue 1557](https://github.com/Sloeber/arduino-eclipse-plugin/issues/1557)
When using `tar.gz` instead of `zip` the Linux file permissions are preserved (i.e. `sloeber-ide`, `jexec`, and `jspawnhelper` are all executable).
**The download page at [http://eclipse.baeyens.it/stable.php?OS=Linux](http://eclipse.baeyens.it/stable.php?OS=Linux) also needs to be updated with the new filename.**  The text saying to run `chmod` can be removed.
* Fixed executable paths in `build_then_launch.sh` (paths are case-sensitive on Linux *et al.*)
* Added note about requiring Java 17 to top-level `readme.md`
This fixes [issue …

Various fixes

---

io.sloeber.core/src/io/sloeber/arduinoFramework/api/LibraryManager.java
io.sloeber.core/src/io/sloeber/core/api/SloeberProject.java
io.sloeber.core/src/io/sloeber/core/internal/ArduinoPrivateHardwareLibraryVersion.java
io.sloeber.core/src/io/sloeber/core/internal/SloeberConfiguration.java
io.sloeber.tests/src/io/sloeber/core/BuildTests.java

Still working on this.
But the unit test is failing (because it is not failing) so want to trigger the build here to se whether the tests is ok (should fail)

Private libraries not working properly #1723
